name: googleSheetMenuWithoutOGP_master

on:
  repository_dispatch:
    types: [googleSheetMenuWithoutOGP]

jobs:
  deploy_production:
    runs-on: macos-latest
    steps:
      - name: Setup Timezone
        run: |
          sudo systemsetup -settimezone Asia/Tokyo
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'
      - name: restore node_modules
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-14-16-node_modules-${{ hashFiles('yarn.lock') }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-14-16-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Copy data.json to master
        run: |
          curl -o data/daily_positive_detail.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/gh-pages/daily_positive_detail.json
          curl -o data/data.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/gh-pages/data.json
          curl -o data/patient_municipalities.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/gh-pages/patient_municipalities.json
          curl -o data/positive_by_diagnosed.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/gh-pages/positive_by_diagnosed.json
          curl -o data/positive_rate.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/gh-pages/positive_rate.json
          curl -o data/positive_status.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/gh-pages/positive_status.json
          curl -o data/news.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/gh-pages/news.json
          curl -o data/alert.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/gh-pages/alert.json
          curl -o data/self_disclosures.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/gh-pages/self_disclosures.json
          curl -o data/main_summary.json https://raw.githubusercontent.com/suzuryo/covid19-iwate-data-bot/gh-pages/main_summary.json
      - name: yarn run generate:deploy for generate OGP
        run: |
          echo "GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}" >> .env.production
          cat .env.production
          yarn run generate:deploy --fail-on-page-error
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          TZ: Asia/Tokyo
      - name: Commit JSON files to master
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status | grep modified && git add data && git commit -v -m "[Bot] update data/*.json at $(date +'%Y-%m-%dT%H:%M:%S%z')"
      - name: Push changes to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      - name: production deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: production
      - name: sitemap ping to google
        run: |
          curl "https://www.google.com/ping?sitemap=https://iwate.stopcovid19.jp/sitemap.xml"
